- name: Check if database secret already exists
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ openshift_namespace }}"
    name: "{{ app }}-db-credentials"
  register: existing_db_secret

- name: Generate database credentials if secret doesn't exist
  block:
    - name: Generate random database credentials
      ansible.builtin.set_fact:
        db_user: "{{ app }}-user"
        db_name: "{{ app }}-db"
        db_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=128') }}"
      when: existing_db_secret.resources | length == 0

    - name: Create database secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ app }}-db-credentials"
            namespace: "{{ openshift_namespace }}"
            labels:
              app: "{{ app }}"
              cnpg.io/reload: "true"
          type: kubernetes.io/basic-auth
          data:
            username: "{{ db_user | b64encode }}"
            password: "{{ db_password  | b64encode }}"
            database: "{{ db_name | b64encode }}"
      when: existing_db_secret.resources | length == 0



- name: Create database secret with random credentials
  kubernetes.core.k8s:
      state: present
      definition:
          apiVersion: v1
          kind: Secret
          metadata:
              name: '{{ app }}-db-credentials'
              namespace: '{{ openshift_namespace }}'
          type: Opaque
          data:
              username: '{{ db_user_b64 }}'
              password: '{{ db_password_b64 }}'
              database: '{{ db_name_b64 }}'

- name: Create database and user in PostgreSQL cluster
  kubernetes.core.k8s:
      state: present
      definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: Database
          metadata:
              name: '{{ app }}-database'
              namespace: '{{ openshift_namespace }}'
          spec:
              cluster:
                  name: postgres-cluster
              name: '{{ db_name }}'
              owner: '{{ db_user }}'
              ownerSecret:
                  name: '{{ app }}-db-credentials'
