registry: quay-its.epfl.ch
organisation: svc0176
image: outlinewiki
version: 0.82.0
app: outlinewiki
subdomain: wiki
db_host: postgres-cluster-rw

secrets: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_idevfsd/fsd-ops/outlinewiki/secrets.yml') | from_yaml }}"
