- name: Create Volume
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "hedgedoc-uploads"
        namespace: "svc0176t-isas-fsd"
      spec:
        storageClassName: "sopec"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
